### ISSUE TITLE
你好，请教一个有关于python orm中数据库表的问题。

### ISSUE THREAD

**Issue by xijiangtao** [wlixcc/pythonORM#1]
在orm写完以后，我不知道你具体是怎么测试的，但我这边需要手动在mysql中创建数据库，然后再创建数据表，请问你也是这样的么？
不论你有没有回答，在此表示感谢。

**Comment by wlixcc** [comment]
这个是肯定的，代码中并没有自动创建表的部分。有需求的话要自行添加这部分代码，教程里说明过的。数据库需要自己创建，教程中提供了sql脚本用来创建表。。
